service: dynamodbToIot
frameworkVersion: ">=1.18.1"
custom:
  appName: dynamodbToIot
  accountId: ${env:AWS_ACCOUNTID}
  endpoint: ${env:AWS_IOT_ENDPOINT}
  topicName: ${env:AWS_IOT_TOPIC}
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  role: execLambdaRole
package:
  individually: true
  exclude:
    - '**/*'
functions:
  # sendMessageToIot
  sendMessageToIot: ${file(./functions/sendMessageToIot/index.yml)}
resources:
  Resources:
    #==========DynamoDB=========
    messages: ${file(./resources/dynamodb/messages.yml)}
    # ==========IAM=========
    execLambdaRole: ${file(./resources/iam/execLambda.yml)}
